src/main/java/com/codegen/cody/modules/gen/entity/GenCategory.java
/**
 * Copyright &copy; 2012-2014 <a href="https://github.com/codegen/cody">Cody</a> All rights reserved.
 */
package com.codegen.cody.modules.gen.entity;

import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

import com.codegen.cody.modules.sys.entity.Dict;

/**
 * 生成方案Entity
 * @author Codegen
 * @version 2013-10-15
 */
@XmlRootElement(name="category")
public class GenCategory extends Dict {
	
	private static final long serialVersionUID = 1L;
	private List<String> template;			// 主表模板
	private List<String> childTableTemplate;// 子表模板
	
	public static String CATEGORY_REF = "category-ref:";

	public GenCategory() {
		super();
	}

	@XmlElement(name = "template")
	public List<String> getTemplate() {
		return template;
	}

	public void setTemplate(List<String> template) {
		this.template = template;
	}
	
	@XmlElementWrapper(name = "childTable")
	@XmlElement(name = "template")
	public List<String> getChildTableTemplate() {
		return childTableTemplate;
	}

	public void setChildTableTemplate(List<String> childTableTemplate) {
		this.childTableTemplate = childTableTemplate;
	}
	
}

src/main/java/com/codegen/cody/modules/gen/entity/GenTableColumn.java
/**
 * Copyright &copy; 2012-2014 <a href="https://github.com/codegen/cody">Cody</a> All rights reserved.
 */
package com.codegen.cody.modules.gen.entity;

import java.util.List;

import org.hibernate.validator.constraints.Length;

import com.google.common.collect.Lists;
import com.codegen.cody.common.persistence.DataEntity;
import com.codegen.cody.common.utils.StringUtils;

/**
 * 业务表字段Entity
 * @author Codegen
 * @version 2013-10-15
 */
public class GenTableColumn extends DataEntity<GenTableColumn> {
	
	private static final long serialVersionUID = 1L;
	private GenTable genTable;	// 归属表
	private String name; 		// 列名
	private String comments;	// 描述
	private String jdbcType;	// JDBC类型
	private String javaType;	// JAVA类型
	private String javaField;	// JAVA字段名
	private String isPk;		// 是否主键（1：主键）
	private String isNull;		// 是否可为空（1：可为空；0：不为空）
	private String isInsert;	// 是否为插入字段（1：插入字段）
	private String isEdit;		// 是否编辑字段（1：编辑字段）
	private String isList;		// 是否列表字段（1：列表字段）
	private String isQuery;		// 是否查询字段（1：查询字段）
	private String queryType;	// 查询方式（等于、不等于、大于、小于、范围、左LIKE、右LIKE、左右LIKE）
	private String showType;	// 字段生成方案（文本框、文本域、下拉框、复选框、单选框、字典选择、人员选择、部门选择、区域选择）
	private String dictType;	// 字典类型
	private Integer sort;		// 排序（升序）
	private String referenceTable;//关联的表
	private String referenceEntity;//关联的实体
	private String referenceField;//关联字段|显示字段

	public GenTableColumn() {
		super();
	}

	public GenTableColumn(String id){
		super(id);
	}
	
	public GenTableColumn(GenTable genTable){
		this.genTable = genTable;
	}

	public GenTable getGenTable() {
		return genTable;
	}

	public void setGenTable(GenTable genTable) {
		this.genTable = genTable;
	}
	
	@Length(min=1, max=200)
	public String getName() {
		return StringUtils.lowerCase(name);
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getJdbcType() {
		return StringUtils.lowerCase(jdbcType);
	}

	public void setJdbcType(String jdbcType) {
		this.jdbcType = jdbcType;
	}

	public String getJavaType() {
		return javaType;
	}

	public void setJavaType(String javaType) {
		this.javaType = javaType;
	}

	public String getJavaField() {
		return javaField;
	}

	public void setJavaField(String javaField) {
		this.javaField = javaField;
	}

	public String getIsPk() {
		return isPk;
	}

	public void setIsPk(String isPk) {
		this.isPk = isPk;
	}

	public String getIsNull() {
		return isNull;
	}

	public void setIsNull(String isNull) {
		this.isNull = isNull;
	}

	public String getIsInsert() {
		return isInsert;
	}

	public void setIsInsert(String isInsert) {
		this.isInsert = isInsert;
	}

	public String getIsEdit() {
		return isEdit;
	}

	public void setIsEdit(String isEdit) {
		this.isEdit = isEdit;
	}

	public String getIsList() {
		return isList;
	}

	public void setIsList(String isList) {
		this.isList = isList;
	}

	public String getIsQuery() {
		return isQuery;
	}

	public void setIsQuery(String isQuery) {
		this.isQuery = isQuery;
	}

	public String getQueryType() {
		return queryType;
	}

	public void setQueryType(String queryType) {
		this.queryType = queryType;
	}

	public String getShowType() {
		return showType;
	}

	public void setShowType(String showType) {
		this.showType = showType;
	}

	public String getDictType() {
		return dictType == null ? "" : dictType;
	}

	public void setDictType(String dictType) {
		this.dictType = dictType;
	}

	public Integer getSort() {
		return sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getReferenceTable() {
		return referenceTable;
	}

	public void setReferenceTable(String referenceTable) {
		this.referenceTable = referenceTable;
	}

	public String getReferenceEntity() {
		return referenceEntity;
	}

	public void setReferenceEntity(String referenceEntity) {
		this.referenceEntity = referenceEntity;
	}

	public String getReferenceField() {
		return referenceField;
	}

	public void setReferenceField(String referenceField) {
		this.referenceField = referenceField;
	}

	/**
	 * 获取列名和说明
	 * @return
	 */
	public String getNameAndComments() {
		return getName() + (comments == null ? "" : "  :  " + comments);
	}
	
	/**
	 * 获取字符串长度
	 * @return
	 */
	public String getDataLength(){
		String[] ss = StringUtils.split(StringUtils.substringBetween(getJdbcType(), "(", ")"), ",");
		if (ss != null && ss.length == 1){// && "String".equals(getJavaType())){
			return ss[0];
		}
		return "0";
	}

	/**
	 * 获取简写Java类型
	 * @return
	 */
	public String getSimpleJavaType(){
		if ("This".equals(getJavaType())){
			return StringUtils.capitalize(genTable.getClassName());
		}
		return StringUtils.indexOf(getJavaType(), ".") != -1 
				? StringUtils.substringAfterLast(getJavaType(), ".")
						: getJavaType();
	}
	
	/**
	 * 获取简写Java字段
	 * @return
	 */
	public String getSimpleJavaField(){
		return StringUtils.substringBefore(getJavaField(), ".");
	}
	
	/**
	 * 获取Java字段，如果是对象，则获取对象.附加属性1
	 * @return
	 */
	public String getJavaFieldId(){
		return StringUtils.substringBefore(getJavaField(), "|");
	}
	
	/**
	 * 获取Java字段，如果是对象，则获取对象.附加属性2
	 * @return
	 */
	public String getJavaFieldName(){
		String[][] ss = getJavaFieldAttrs();
		return ss.length>0 ? getSimpleJavaField()+"."+ss[0][0] : "";
	}
	
	/**
	 * 获取Java字段，所有属性名
	 * @return
	 */
	public String[][] getJavaFieldAttrs(){
		String[] ss = StringUtils.split(StringUtils.substringAfter(getJavaField(), "|"), "|");
		String[][] sss = new String[ss.length][2];
		if (ss!=null){
			for (int i=0; i<ss.length; i++){
				sss[i][0] = ss[i];
				sss[i][1] = StringUtils.toUnderScoreCase(ss[i]);
			}
		}
		return sss;
	}
	
	/**
	 * 获取列注解列表
	 * @return
	 */
	public List<String> getAnnotationList(){
		List<String> list = Lists.newArrayList();
		// 导入Jackson注解
		if ("This".equals(getJavaType())){
			list.add("com.fasterxml.jackson.annotation.JsonBackReference");
		}
		if ("java.util.Date".equals(getJavaType())){
			list.add("com.fasterxml.jackson.annotation.JsonFormat(pattern = \"yyyy-MM-dd HH:mm:ss\")");
		}
		// 导入JSR303验证依赖包
		if (!"1".equals(getIsNull()) && !"String".equals(getJavaType())){
			list.add("javax.validation.constraints.NotNull(message=\""+getComments()+"不能为空\")");
		}
		else if (!"1".equals(getIsNull()) && "String".equals(getJavaType()) && !"0".equals(getDataLength())){
			list.add("org.hibernate.validator.constraints.Length(min=1, max="+getDataLength()
					+", message=\""+getComments()+"长度必须介于 1 和 "+getDataLength()+" 之间\")");
		}
		else if ("String".equals(getJavaType()) && !"0".equals(getDataLength())){
			list.add("org.hibernate.validator.constraints.Length(min=0, max="+getDataLength()
					+", message=\""+getComments()+"长度必须介于 0 和 "+getDataLength()+" 之间\")");
		}
		return list;
	}
	
	/**
	 * 获取简写列注解列表
	 * @return
	 */
	public List<String> getSimpleAnnotationList(){
		List<String> list = Lists.newArrayList();
		for (String ann : getAnnotationList()){
			list.add(StringUtils.substringAfterLast(ann, "."));
		}
		return list;
	}
	
	/**
	 * 是否是基类字段
	 * @return
	 */
	public Boolean getIsNotBaseField(){
		return StringUtils.equals(getSimpleJavaField(), "id");
	}
	
}

src/main/java/com/codegen/cody/modules/gen/web/GenSchemeController.java
/**
 * Copyright &copy; 2012-2014 <a href="https://github.com/codegen/cody">Cody</a> All rights reserved.
 */
package com.codegen.cody.modules.gen.web;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.codegen.cody.common.config.Global;
import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import com.codegen.cody.common.persistence.Page;
import com.codegen.cody.common.utils.StringUtils;
import com.codegen.cody.common.web.BaseController;
import com.codegen.cody.modules.sys.entity.User;
import com.codegen.cody.modules.sys.utils.UserUtils;
import com.codegen.cody.modules.gen.entity.GenScheme;
import com.codegen.cody.modules.gen.service.GenSchemeService;
import com.codegen.cody.modules.gen.service.GenTableService;
import com.codegen.cody.modules.gen.util.GenUtils;

/**
 * 生成方案Controller
 * @author Codegen
 * @version 2013-10-15
 */
@Controller
@RequestMapping(value = "${adminPath}/gen/genScheme")
public class GenSchemeController extends BaseController {

	@Autowired
	private GenSchemeService genSchemeService;
	
	@Autowired
	private GenTableService genTableService;
	
	@ModelAttribute
	public GenScheme get(@RequestParam(required=false) String id) {
		if (StringUtils.isNotBlank(id)){
			return genSchemeService.get(id);
		}else{
			return new GenScheme();
		}
	}
	
	@RequiresPermissions("gen:genScheme:view")
	@RequestMapping(value = {"list", ""})
	public String list(GenScheme genScheme, HttpServletRequest request, HttpServletResponse response, Model model) {
		User user = UserUtils.getUser();
		if (!user.isAdmin()){
			genScheme.setCreateBy(user);
		}
        Page<GenScheme> page = genSchemeService.find(new Page<GenScheme>(request, response), genScheme); 
        model.addAttribute("page", page);
		
		return "modules/gen/genSchemeList";
	}

	@RequiresPermissions("gen:genScheme:view")
	@RequestMapping(value = "form")
	public String form(GenScheme genScheme, Model model) {
		if (StringUtils.isBlank(genScheme.getPackageName())){
			String projectPath = Global.getConfig("basePackageName");
			genScheme.setPackageName(projectPath);
		}
//		if (StringUtils.isBlank(genScheme.getFunctionAuthor())){
//			genScheme.setFunctionAuthor(UserUtils.getUser().getName());
//		}
		model.addAttribute("genScheme", genScheme);
		model.addAttribute("config", GenUtils.getConfig());
		model.addAttribute("tableList", genTableService.findAll());
		return "modules/gen/genSchemeForm";
	}

	@RequiresPermissions("gen:genScheme:edit")
	@RequestMapping(value = "save")
	public String save(GenScheme genScheme, Model model, RedirectAttributes redirectAttributes) {
		if (!beanValidator(model, genScheme)){
			return form(genScheme, model);
		}
		User user = UserUtils.getUser();
		genScheme.setFunctionAuthor(user.getName());
		String result = genSchemeService.save(genScheme);
		addMessage(redirectAttributes, "操作生成方案'" + genScheme.getName() + "'成功<br/>"+result);
		return "redirect:" + adminPath + "/gen/genScheme/?repage";
	}
	
	@RequiresPermissions("gen:genScheme:edit")
	@RequestMapping(value = "delete")
	public String delete(GenScheme genScheme, RedirectAttributes redirectAttributes) {
		genSchemeService.delete(genScheme);
		addMessage(redirectAttributes, "删除生成方案成功");
		return "redirect:" + adminPath + "/gen/genScheme/?repage";
	}

}

src/main/java/com/codegen/cody/modules/gen/web/GenTableController.java
/**
 * Copyright &copy; 2012-2014 <a href="https://github.com/codegen/cody">Cody</a> All rights reserved.
 */
package com.codegen.cody.modules.gen.web;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import com.codegen.cody.common.persistence.Page;
import com.codegen.cody.common.utils.StringUtils;
import com.codegen.cody.common.web.BaseController;
import com.codegen.cody.modules.sys.entity.User;
import com.codegen.cody.modules.sys.utils.UserUtils;
import com.codegen.cody.modules.gen.entity.GenTable;
import com.codegen.cody.modules.gen.service.GenTableService;
import com.codegen.cody.modules.gen.util.GenUtils;

/**
 * 业务表Controller
 * @author Codegen
 * @version 2013-10-15
 */
@Controller
@RequestMapping(value = "${adminPath}/gen/genTable")
public class GenTableController extends BaseController {

	@Autowired
	private GenTableService genTableService;
	
	@ModelAttribute
	public GenTable get(@RequestParam(required=false) String id) {
		if (StringUtils.isNotBlank(id)){
			return genTableService.get(id);
		}else{
			return new GenTable();
		}
	}
	
	@RequiresPermissions("gen:genTable:view")
	@RequestMapping(value = {"list", ""})
	public String list(GenTable genTable, HttpServletRequest request, HttpServletResponse response, Model model) {
		User user = UserUtils.getUser();
		if (!user.isAdmin()){
			genTable.setCreateBy(user);
		}
        Page<GenTable> page = genTableService.find(new Page<GenTable>(request, response), genTable); 
        model.addAttribute("page", page);
		return "modules/gen/genTableList";
	}

	@RequiresPermissions("gen:genTable:view")
	@RequestMapping(value = "form")
	public String form(GenTable genTable, Model model) {
		// 获取物理表列表
		List<GenTable> tableList = genTableService.findTableListFormDb(new GenTable());
		model.addAttribute("tableList", tableList);
		// 验证表是否存在
		if (StringUtils.isBlank(genTable.getId()) && !genTableService.checkTableName(genTable.getName())){
			addMessage(model, "下一步失败！" + genTable.getName() + " 表已经添加！");
			genTable.setName("");
		}
		// 获取物理表字段
		else{
			genTable = genTableService.getTableFormDb(genTable);
		}
		model.addAttribute("genTable", genTable);
		model.addAttribute("config", GenUtils.getConfig());
		return "modules/gen/genTableForm";
	}

	@RequiresPermissions("gen:genTable:edit")
	@RequestMapping(value = "save")
	public String save(GenTable genTable, Model model, RedirectAttributes redirectAttributes) {
		if (genTable.getImportExcel() == null){
			genTable.setImportExcel("0");
		}
		if (genTable.getExportExcel() == null){
			genTable.setExportExcel("0");
		}
		if (!beanValidator(model, genTable)){
			return form(genTable, model);
		}
		// 验证表是否已经存在
		if (StringUtils.isBlank(genTable.getId()) && !genTableService.checkTableName(genTable.getName())){
			addMessage(model, "保存失败！" + genTable.getName() + " 表已经存在！");
			genTable.setName("");
			return form(genTable, model);
		}
		genTableService.save(genTable);
		addMessage(redirectAttributes, "保存业务表'" + genTable.getName() + "'成功");
		return "redirect:" + adminPath + "/gen/genTable/?repage";
	}
	
	@RequiresPermissions("gen:genTable:edit")
	@RequestMapping(value = "delete")
	public String delete(GenTable genTable, RedirectAttributes redirectAttributes) {
		genTableService.delete(genTable);
		addMessage(redirectAttributes, "删除业务表成功");
		return "redirect:" + adminPath + "/gen/genTable/?repage";
	}

}

src/main/resources/templates/modules/gen/curd/temp.ftl
<?xml version="1.0" encoding="utf-8"?>
<template>
    <name>viewList</name>
    <filePath>src/main/webapp/WEB-INF/page/${className}</filePath>
    <fileName>${className}-list.jsp</fileName>
    <content><![CDATA[
        <%@ page contentType="text/html;charset=UTF-8" language="java" %>
        <%@include file="/jspf/fn.jspf" %>

        <!DOCTYPE HTML>
        <html>

        <head>

            <%@include file="/jspf/list-meta.jspf" %>

            <title>${genScheme.name}</title>

        </head>

        <body>
        <nav class="breadcrumb">
            <i class="Hui-iconfont">&#xe67f;</i> 首页
            <span class="c-gray en">&gt;</span>  系统配置
            <span class="c-gray en">&gt;</span>  ${genScheme.name}
            <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px"
               href="javascript:location.replace(location.href);" title="刷新">
                <i class="Hui-iconfont">&#xe68f;</i></a>
        </nav>
        <div class="page-container">

            <!-- 条件筛选 -->
            <div class="search-container bg-F9">
                <form id="bsSearchForm" action="#" method="post" class="form form-horizontal" onsubmit="javacript:return false;">
                    <div class="cl">
                    <#list table.columnList as c>
                        <#if c.isQuery?? && c.isQuery == "1">
                            <#if c.showType == "select">
                                <div class="col-lg-3 col-md-4 col-sm-6 mt-10 mb-10">
                                    <label class="form-label col-sm-5 text-r">${c.comments}：</label>
                                    <div class="formControls col-sm-7">
                                        <select name="QUERY-${c.simpleJavaField}-s-eq" class="input-text">
                                            <option value="">---请选择---</option>
                                            <c:forEach items="${"$"}{dict:getByType('${c.dictType}')}" var="item">
                                                <option value="${"$"}{item.code}">${"$"}{item.name}</option>
                                            </c:forEach>
                                        </select>
                                    </div>
                                </div>
                            <#elseif c.javaType == "java.util.Date">
                                <label class="form-label col-xs-3 col-sm-3">${c.comments}：</label>
                                <div class="formControls col-xs-3 col-sm-3">
                                    <input type="text" value="<fmt:formatDate value="${"$"}{vo.${c.javaField}}" pattern="yyyy/MM/dd"></fmt:formatDate>" name="QUERY-create_date-s-ge" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd'})"
                                    class="input-text Wdate" style="width:205px;" readonly>至
                                    <input type="text" value="<fmt:formatDate value="${"$"}{vo.${c.javaField}}" pattern="yyyy/MM/dd"></fmt:formatDate>" name="QUERY-create_date-s-le" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd'})"
                                    class="input-text Wdate" style="width:205px;" readonly>
                                </div>
                            <#elseif c.showType != "pictureselect">
                                <div class="col-lg-3 col-md-4 col-sm-6 mt-10 mb-10">
                                    <label class="form-label col-sm-5 text-r">${c.comments}：</label>
                                    <div class="formControls col-sm-7">
                                        <input type="text" class="input-text radius size-S" value="" placeholder="" name="QUERY-${c.name}-s-<#if c.queryType == "=">eq<#elseif c.queryType == "like">lk<#elseif c.queryType == "!=">ne<#elseif c.queryType == "&gt;">gt<#elseif c.queryType == "&gt;=">ge<#elseif c.queryType == "&lt;">lt<#elseif c.queryType == "&lt;=">le<#elseif c.queryType == "in">in<#elseif c.queryType == "is">is<#elseif c.queryType == "notLike">nlk</#if>">
                                    </div>
                                </div>
                            </#if>
                        </#if>
                    </#list>
                        <div class="col-lg-3 col-md-4 col-sm-6 mt-10 mb-10">
                            <div class=" col-sm-12">
                                <a class="btn btn-primary radius ml-15" id="bsSearch"><i class="Hui-iconfont">&#xe665;</i> 搜索
                                </a>
                                <a class="btn btn-primary radius ml-15" id="bsReset"><i class="Hui-iconfont">&#xe66c;</i> 重置
                                </a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- 条件筛选结束 -->

            <!-- 工具栏 -->
            <div class="cl pd-5 bg-F9 bk-gray mt-10 pd-10">
        <span class="l">
            <my:p code="${className}_del">
                <button onclick="delAll()" class="btn btn-danger  radius size-S ml-10">
                    <i class="Hui-iconfont"> &#xe6e2;</i> 批量删除
                </button>
            </my:p>

            <my:p code="${className}_edit">
                <button onclick="add()" class="btn btn-success radius size-S ml-10">
                    <i class="Hui-iconfont">&#xe600;</i> 添加
                </button>
            </my:p>

        <#if excel == "1">
            <span class="${className}_excel">
                <button onclick="exportExcel()" class="btn btn-success radius size-S ml-10">
                    导出
                </button>
            </span>
        </#if>

        </span>
            </div>

            <!-- 表格 -->
            <!--index是直接调用属性的，render调用的属性需要有方法-->
            <div class="mt-10">
                <table id="bsGrid" class="bs-grid">
                    <tr>
                        <th w_index="id" w_check="true" width="1%;"></th>
                    <#list table.columnList as c>
                        <#if c.name != "id" && c.isList == "1">
                            <#if c.showType == "pictureselect" || c.javaType == "java.util.Date">
                                <th w_render="${c.javaField}" w_sort="${c.name}" w_align="center" width="10%;">${c.comments}</th>
                            <#else>
                                <th w_index="${c.javaField}" w_sort="${c.name}" w_align="center" width="10%;">${c.comments}</th>
                            </#if>
                        </#if>
                    </#list>
                        <th w_render="toolbar" w_align="center" width="8%;">操作</th>
                    </tr>
                </table>
            </div>
        </div>

        <%@include file="/jspf/list-footer.jspf" %>
        <%--时间控件--%>
        <script type="text/javascript" src="${"$"}{ctx}/plugins/lib/My97DatePicker/WdatePicker.js"></script>

        <script type="text/javascript">
            function toolbar(row) {
                var id = row.id;
                var html = "";

            <my:p code="${className}_edit">
                html += '<a title="编辑" href="javascript:;" onclick="add(' + id + ')" ><i class="Hui-iconfont">&#xe6df;</i>编辑</a>'
                        </my:p>

                <my:p code="${className}_del">
                html += '<a title="删除" href="javascript:;" onclick="del(' + id + ')" class="ml-15"><i class="Hui-iconfont">&#xe6e2;</i>删除</a>';
            </my:p>

                return html;
            }
            <#list table.columnList as c>
                <#if c.showType == "select" || c.showType == "radiobox" || c.showType == "checkbox" ||>
                /** 显示对应中文类型 **/
                var ${c.javaField}Object = ${dict:getJSONByType("${c.dictType}")};
                function ${c.javaField}(row) {
                    if(${c.javaField}Object[row.${c.javaField}]){
                        return ${c.javaField}Object[${c.javaField}];
                    }else{
                        return "";
                    }
                }
                </#if>
            </#list>


            <#list table.columnList as c>
                <#if c.javaType == "java.util.Date">
                /** 显示时间格式 **/
                function ${c.javaField}(row) {
                    if (${c.javaField} != null){
                    return new Date(row["${c.javaField}"]).format(<#if c.isEdit == "1">'yyyy-MM-dd'<#else>'yyyy-MM-dd hh:mm:ss'</#if>);
                    } else {
                        return "";
                    }
                }
                </#if>
            </#list>

            <#if excel == "1">
            function exportExcel() {
                var params = $('#bsSearchForm').serialize();
                location.href = "${"$"}{basePath}/b/${className}/${className}Ex?" + params;
            }
            </#if>

            <#list table.columnList as c>
                <#if c.showType == "pictureselect">
                /** 图片显示 **/
                function ${c.javaField}(row) {
                    var ${c.javaField} = row.${c.javaField};
                    if(${c.javaField}){
                        var ${c.javaField}Url = "${"$"}{staticAddressUrl}"+row.${c.javaField};
                        return "<img width='50' height='50' src="+${c.javaField}Url+" />";
                    }else{
                        return "";
                    }
                }
                </#if>
            </#list>

            /** 获取列表数据 **/
            var gridObj;
            $(function () {
                gridObj = BSGrid.init('bsGrid', {
                    url: '${"$"}{ctx}/b/${className}/list',
                    otherParames: $('#bsSearchForm').serializeArray(),
                });

            });

            /** 跳转编辑框 **/
            function add(id) {
                var url = "${"$"}{ctx}/b/${className}/editUI?id=";
                if (id) {
                    url += id;
                }
                layer_show("编辑", url, 800, 650);
            }

            /** 删除 **/
            function del(id) {
                xxl.confirm("确认要删除吗？", function (index) {
                    $.get('${"$"}{ctx}/b/${className}/del?id=' + id, function (result) {
                        if (result == "success") {
                            xxl.sucRef();
                        }
                    })
                });
            }

            /** 批量删除 **/
            function delAll() {
                var ids = BSGrid.getCheckedRowsId(gridObj);
                if (!ids) {
                    xxl.message("请至少选中一行 !", 2);
                    return;
                }
                xxl.confirm("确定要删除选中项吗?", function () {
                    $.get("${"$"}{ctx}/b/${className}/delAll?ids=" + ids, function (result) {
                        if (result == "success") {
                            xxl.sucRef();
                        }
                    })
                });
            }

        </script>
        </body>

        </html>]]>
    </content>
</template>